Deployment status formatting + default request config
friendliai/periflow-cli pull request #150
Opened 2023-03-31 05:15 UTC by kooyunmo

2023-04-04 06:23 UTC, kdh0102 requested changes
Nice work! A few minor comments.

2023-04-04 06:23 UTC, kdh0102 commented on pfcli/deployment.py
> +        None, "--default-request-config-file", help="Path to default request config"
```suggestion
        None, "--default-request-config-file", "-drc", help="Path to default request config"
```

2023-04-04 06:23 UTC, kdh0102 commented on pfcli/deployment.py
> +        file_size = os.stat(default_request_config_file.name).st_size
Any limit on the file size?

2023-04-05 02:30 UTC, pigbug419 approved these changes
LGTM!

2023-04-05 02:30 UTC, pigbug419 commented on pfcli/deployment.py
> +        file_size = os.stat(default_request_config_file.name).st_size
I suggest 5~10MB 😄

2023-04-05 08:52 UTC, merged