[PF-1394] split predefined and custom config
friendliai/periflow-cli pull request #155
Opened 2023-04-11 02:58 UTC by ktaebum

2023-04-13 06:04 UTC, kooyunmo requested changes

2023-04-13 06:04 UTC, kooyunmo commented on VERSION
> +0.1.18
The version is already updated to 0.1.18 in main branch. Please do `git stash` for this file or pull the main branch.

2023-04-13 06:04 UTC, kooyunmo commented on pfcli/service/config.py
At the last week, `pfcli/service/config.py` is separated into multiple files in `pfcli/configurator`. Can you please apply the change you made in this file to https://github.com/friendliai/periflow-cli/blob/main/pfcli/configurator/job.py?

2023-04-19 06:31 UTC, kooyunmo commented
@ktaebum I created a new PR that applies the most up-to-date schema in PR #163. Can I close this PR?

2023-04-19 06:43 UTC, ktaebum commented
Close by #163

2023-04-19 06:43 UTC, closed without merging