MFA
friendliai/periflow-cli pull request #73
Opened 2022-09-05 13:30 UTC by creeper00

2022-09-07 14:01 UTC, kooyunmo requested changes
I just left one minor comment! Everything else LGTM!

2022-09-07 23:56 UTC, creeper00 commented on pfcli/main.py
> +        client: UserClientService = build_client(ServiceType.MFA)
Oh, thanks for finding. My mistake

2022-09-08 00:03 UTC, kooyunmo commented
@creeper00 Can you please resolve the conflict before merge?

2022-09-08 05:33 UTC, kooyunmo approved these changes
LGTM!

2022-09-08 05:33 UTC, merged